### ISSUE TITLE
This doesn't actually work

### ISSUE THREAD

**Issue by CoolOppo** [gmodcoders/wsdl#6]

**Comment by storm37000** [comment]
it works fine for me, what error are you getting?

**Comment by Kiwi-i** [comment]
After removing all my addons to try and solve some compat issue I ran into the same thing where it seemingly does not register the "resource.AddWorkshop()" from the script, no errors and I haven't attempted any debugging.
I manually created a resources.lua file and without doing anything else made all the addons download fine.
I'm running both a 64bit client architecture and the 64bit server architecture.

This issue is weird, since the addon seemed to be working fine not too long ago, and no idea if there was some unmentioned change to how adding resources works.

**Comment by storm37000** [comment]
This does nothing with other addons' resource.AddWorkshop, you might be running into the limit for how many addons can be added with that function.
